execute pathogen#infect()
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

set nocompatible
filetype indent plugin on
syntax on

let g:molokai_original = 1

set ruler "shows line and column of the cursor"
set tabstop=4 "tab 4 spaces"
set shiftwidth=4 "number of spaces to use when auto indent
set expandtab
"set smartindent
set showmatch
"set t_Co=256

function! NumberToggle()
    if(&relativenumber == 1)
        set nornu
        set nonu
    else
        set rnu
        set nu
    endif
endfunc

nnoremap <C-n> :call NumberToggle()<cr>
